"""Initial

Revision ID: 46e42baf25b2
Revises: 
Create Date: 2021-12-11 01:09:10.482251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e42baf25b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('sex', sa.SmallInteger(), nullable=False),
    sa.Column('attr', sa.SmallInteger(), nullable=False),
    sa.Column('deptid', sa.SmallInteger(), nullable=False),
    sa.Column('localid', sa.Integer(), nullable=False),
    sa.Column('idmanager', sa.BigInteger(), nullable=False),
    sa.Column('timeUpdate', sa.BigInteger(), nullable=False),
    sa.Column('delete', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_attr'), 'user', ['attr'], unique=False)
    op.create_index(op.f('ix_user_delete'), 'user', ['delete'], unique=False)
    op.create_index(op.f('ix_user_deptid'), 'user', ['deptid'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_idmanager'), 'user', ['idmanager'], unique=False)
    op.create_index(op.f('ix_user_localid'), 'user', ['localid'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_number'), 'user', ['number'], unique=True)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_index(op.f('ix_user_timeUpdate'), 'user', ['timeUpdate'], unique=False)
    op.create_table('user_photo',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('idmanager', sa.BigInteger(), nullable=False),
    sa.Column('timeUpdate', sa.BigInteger(), nullable=False),
    sa.Column('delete', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_photo_delete'), 'user_photo', ['delete'], unique=False)
    op.create_index(op.f('ix_user_photo_id'), 'user_photo', ['id'], unique=False)
    op.create_index(op.f('ix_user_photo_idmanager'), 'user_photo', ['idmanager'], unique=False)
    op.create_index(op.f('ix_user_photo_timeUpdate'), 'user_photo', ['timeUpdate'], unique=False)
    op.create_index(op.f('ix_user_photo_user_id'), 'user_photo', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_photo_user_id'), table_name='user_photo')
    op.drop_index(op.f('ix_user_photo_timeUpdate'), table_name='user_photo')
    op.drop_index(op.f('ix_user_photo_idmanager'), table_name='user_photo')
    op.drop_index(op.f('ix_user_photo_id'), table_name='user_photo')
    op.drop_index(op.f('ix_user_photo_delete'), table_name='user_photo')
    op.drop_table('user_photo')
    op.drop_index(op.f('ix_user_timeUpdate'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_number'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_localid'), table_name='user')
    op.drop_index(op.f('ix_user_idmanager'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_deptid'), table_name='user')
    op.drop_index(op.f('ix_user_delete'), table_name='user')
    op.drop_index(op.f('ix_user_attr'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
